### ISSUE TITLE
Kill Count for Units in Campaign

### ISSUE THREAD

**Issue by Axlegolas** [mklabs/twmods#25]
The unit cards in campaign should have 3 pages..
On page 1 you can see the bullet_points of a unit
On page 2 you can see the historical text
On page 3 there should be an overall kill count.
The kill count of a unit can be seen during a battle and after a battle, we just need to save the value and sum it up, maybe we could show up kills per main_faction, so i know which factions my unit has killed so far.
Tricky will be the UI mod to get another page shown up in the unit card.

**Comment by mklabs** [comment]
This is an awesome idea.

If the 3rd page is not possible, maybe we can think of another UI. (like the encyclopedia when right clicking on the unit card).

You can really go far with it, and have a lot of stats displayed here. Maybe with some graphs or other data representations.

**Comment by mklabs** [comment]
When clicking on unit description button (the arrow to change the page)
```
[ui] <223.8s>   uicomponent button_description_toggle:
[ui] <223.8s>
[ui] <223.8s>   path from root:         root > layout > info_panel_holder > secondary_info_panel_holder > info_panel_background > UnitInfoPopup > top_section > button_description_toggle
[ui] <223.8s>           position on screen:     250, 523
[ui] <223.8s>           size:                   38, 38
[ui] <223.8s>           state:          down
[ui] <223.8s>           visible:                true
[ui] <223.8s>           priority:               46
[ui] <223.8s>
```

**Comment by mklabs** [comment]
This issue was moved to mklabs/taurox-beastmen-mod#14
